name: 🐛 Bug Report
description: Report a bug or issue with the Mergington High School Activities System
title: "[BUG] "
labels: ["bug"]
assignees:
  - "Copilot"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is
      placeholder: "Example: Students can't register for activities when clicking the Register button"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: What area of the system is affected?
      options:
        - Student Activity Registration
        - Teacher Authentication/Login
        - Activity Display/Filtering
        - Student Unregistration
        - User Interface/Design
        - API/Backend Functionality
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this behavior
      placeholder: |
        1. Go to the main activities page
        2. Click on an activity
        3. Click 'Register' button
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen when the system works correctly?
      placeholder: "Example: Student should be successfully registered for the activity and see a confirmation message"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens instead?
      placeholder: "Example: Error message appears saying 'Failed to register' and student is not added to activity"
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency Level
      description: How critical is this bug for daily operations?
      options:
        - High - System is unusable or data is lost
        - Medium - Feature doesn't work but workarounds exist
        - Low - Minor issue that doesn't affect main functionality
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, error messages, etc.)
      placeholder: "Example: This happens only when trying to register students for weekend activities"

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: When can we consider this bug fixed?
      options:
        - label: Bug is reproducible and root cause is identified
        - label: Fix is implemented and tested
        - label: System works as expected without breaking existing functionality
        - label: Teacher can verify the fix works in their workflow

  - type: markdown
    attributes:
      value: |
        ## Implementation Hints
        - Check the relevant API endpoints in `/src/backend/routers/`
        - Look at frontend JavaScript in `/src/static/app.js` for UI issues
        - Verify database operations in `/src/backend/database.py`
        - Test both teacher authentication and student registration flows