blank_issues_enabled: false
contact_links:
  - name: 📚 Development Documentation
    url: https://github.com/antonrademaker/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to set up and develop the Activities System
  - name: 💬 General Questions
    url: https://github.com/antonrademaker/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or discuss ideas about the system