name: ✨ Feature Enhancement
description: Request a new feature or improvement to the Activities System
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - "Copilot"
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request new features or enhancements to make the Activities System more useful for teachers and students.

  - type: input
    id: feature_title
    attributes:
      label: Feature Title
      description: What feature would you like to see added?
      placeholder: "Example: Add ability to export student registration lists"
    validations:
      required: true

  - type: dropdown
    id: feature_area
    attributes:
      label: What area would this feature affect?
      options:
        - Student Registration Management
        - Teacher Dashboard/Tools
        - Activity Management
        - Reporting and Analytics
        - User Interface/User Experience
        - Authentication and Security
        - Data Import/Export
        - Communication/Notifications
        - Search and Filtering
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the current problem or limitation that this feature would address
      placeholder: "Example: Currently teachers have no way to quickly see which students are registered for activities, making it hard to plan and communicate"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: "Example: Add a button on each activity that downloads a CSV file with student names and email addresses"
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Who would primarily use this feature?
      options:
        - Teachers only
        - Students only
        - Both teachers and students
        - System administrators
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature?
      options:
        - High - Critical for daily operations
        - Medium - Would significantly improve workflow
        - Low - Nice to have but not essential
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Example: Could also be implemented as a print-friendly view instead of CSV export"

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mock-ups
      description: Provide examples, sketches, or describe similar features you've seen elsewhere
      placeholder: "Example: Similar to how Google Classroom lets teachers export class rosters"

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: When can we consider this feature complete?
      options:
        - label: Feature works as described in the proposed solution
        - label: Feature is accessible to the intended user type
        - label: Feature integrates well with existing UI/workflow
        - label: Feature doesn't break existing functionality
        - label: Feature is tested and working reliably
        - label: Feature handles edge cases appropriately

  - type: markdown
    attributes:
      value: |
        ## Implementation Hints
        - Consider if this requires new API endpoints in `/src/backend/routers/`
        - Check if UI changes are needed in `/src/static/` files
        - Think about database schema changes in `/src/backend/database.py`
        - Consider authentication requirements for teacher-only features
        - Plan for responsive design if adding new UI elements
        - Consider adding new filters or sorting options if relevant