name: 🎨 UI/UX Improvement
description: Request improvements to the user interface or user experience
title: "[UI/UX] "
labels: ["enhancement", "ui/ux"]
assignees:
  - "Copilot"
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request improvements to the visual design, layout, or user experience of the Activities System.

  - type: input
    id: ui_area
    attributes:
      label: What part of the interface needs improvement?
      description: Specify the page, component, or section
      placeholder: "Example: Activity registration modal dialog"
    validations:
      required: true

  - type: dropdown
    id: improvement_type
    attributes:
      label: What type of improvement is this?
      options:
        - Visual Design (colors, fonts, spacing)
        - Layout and Organization
        - User Experience Flow
        - Accessibility
        - Mobile Responsiveness
        - Performance/Loading
        - Error Messages/Feedback
        - Navigation
        - Other
    validations:
      required: true

  - type: textarea
    id: current_issue
    attributes:
      label: Current Issue
      description: What's wrong with the current design or user experience?
      placeholder: "Example: The registration modal is too small and the form fields are cramped, making it difficult to read and use"
    validations:
      required: true

  - type: textarea
    id: proposed_improvement
    attributes:
      label: Proposed Improvement
      description: How would you like to see it improved?
      placeholder: "Example: Make the modal larger, add more spacing between form fields, and use clearer labels"
    validations:
      required: true

  - type: dropdown
    id: affected_users
    attributes:
      label: Who is affected by this UI issue?
      options:
        - Teachers only
        - Students only
        - Both teachers and students
        - All users
    validations:
      required: true

  - type: dropdown
    id: device_impact
    attributes:
      label: What devices/screens are affected?
      multiple: true
      options:
        - Desktop/Laptop
        - Tablet
        - Mobile Phone
        - All devices
    validations:
      required: true

  - type: textarea
    id: user_impact
    attributes:
      label: How does this impact users?
      description: Describe the specific problems users face with the current design
      placeholder: "Example: Teachers struggle to register students quickly because they have to scroll to see all form fields"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other details, screenshots, or examples that would help?
      placeholder: "Example: This is especially problematic during busy registration periods when teachers need to register many students quickly"

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: When can we consider this improvement complete?
      options:
        - label: Visual/layout improvement is implemented as described
        - label: User experience is smoother and more intuitive
        - label: Design is consistent with the rest of the application
        - label: Improvement works well on all specified devices
        - label: No existing functionality is broken
        - label: Improvement is accessible to users with disabilities
        - label: Teachers can complete their tasks more efficiently

  - type: markdown
    attributes:
      value: |
        ## Implementation Hints
        - UI styles are in `/src/static/style.css` (if it exists) or inline styles
        - HTML structure is in `/src/static/index.html`
        - JavaScript interactions are in `/src/static/app.js`
        - Consider using CSS flexbox or grid for better layouts
        - Test on different screen sizes for responsiveness
        - Use semantic HTML elements for better accessibility
        - Ensure sufficient color contrast for readability
        - Consider loading states and error handling in the UI